DefaultContentLanguage = "en"
author = "Hukum Negi"
baseURL = "https://www.worldx24.com"
copyright = "Copyright © 2020, Worldx24.com; All Rights Reserved."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "casper3"
title = "Worldx24"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "image-credit"
name = "Image Credit"
url = "/image-credit/"
weight = 20
[[menu.main]]
identifier = "github-repo-theme"
name = "Get Theme on Github"
url = "https://github.com/jonathanjanssens/hugo-casper3"
weight = 30
[[menu.main]]
identifier = "author"
name = "Author Homepage"
url = "https://jonathanjanssens.com"
weight = 40
[params]
description = "Wolrd Premium Online Magazine"
facebook = "https://facebook.com/wordx24"
github = "https://github.com/hurockport"
logo = "/images/ghost-transparent.png"
mainSections = ["post"]
twitter = "https://twitter.com/worldx24"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
